### ISSUE TITLE
invalid runtime symbol table crash

### ISSUE THREAD

**Issue by akrylysov** [ianlancetaylor/cgosymbolizer#14]
Enabling cgosymbolizer occasionally causes "invalid runtime symbol table". It happens only sometimes on the same binary. 

Here is the stack trace:
```
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: runtime: invalid pc-encoded table f=runtime.allocm pc=0x5c63f0 targetpc=0x5c63ff tab=[0/0]0x0
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=-1 until pc=0x5c616f
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=0 until pc=0x5c6173
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=-1 until pc=0x5c6174
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=0 until pc=0x5c617a
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=-1 until pc=0x5c619b
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=1 until pc=0x5c619c
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=2 until pc=0x5c61ac
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=-1 until pc=0x5c623f
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=3 until pc=0x5c6240
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=4 until pc=0x5c6250
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=-1 until pc=0x5c62fe
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=5 until pc=0x5c632c
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         value=-1 until pc=0x5c63f0
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: fatal error: invalid runtime symbol table
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: goroutine 337639 [running]:
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: runtime.throw(0x29b99b9, 0x1c)
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         /root/.gimme/versions/go1.15.8.linux.amd64/src/runtime/panic.go:1116 +0x72 fp=0xc075779ac8 sp=0xc075779a98 pc=0x5c0632
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: runtime.pcvalue(0x2eea650, 0x3ff6500, 0xc00012a84f, 0x5c63ff, 0xc075779c28, 0x5ded01, 0x5c63ff, 0x3ff6500)
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         /root/.gimme/versions/go1.15.8.linux.amd64/src/runtime/symtab.go:813 +0x59f fp=0xc075779b78 sp=0xc075779ac8 pc=0x5df49f
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: runtime.pcdatavalue(0x2eea650, 0x3ff6500, 0x2, 0x5c63ff, 0xc075779c28, 0x8f154f)
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         /root/.gimme/versions/go1.15.8.linux.amd64/src/runtime/symtab.go:901 +0x86 fp=0xc075779bc8 sp=0xc075779b78 pc=0x5dfc06
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: runtime/pprof.runtime_expandFinalInlineFrame(0xc0120f94e0, 0x0, 0x1, 0x8f55d7, 0xc0667a2907, 0xc05d222218)
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         /root/.gimme/versions/go1.15.8.linux.amd64/src/runtime/symtab.go:186 +0x186 fp=0xc075779d58 sp=0xc075779bc8 pc=0x5f61a6
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: runtime/pprof.(*profileBuilder).appendLocsForStack(0xc05d222160, 0xc057940a00, 0x0, 0x20, 0xc0120f94e0, 0x1, 0x1, 0x0, 0x2, 0x20)
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         /root/.gimme/versions/go1.15.8.linux.amd64/src/runtime/pprof/proto.go:392 +0x7f fp=0xc075779e08 sp=0xc075779d58 pc=0x8f26ff
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: runtime/pprof.(*profileBuilder).build(0xc05d222160)
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         /root/.gimme/versions/go1.15.8.linux.amd64/src/runtime/pprof/proto.go:365 +0x137 fp=0xc075779f58 sp=0xc075779e08 pc=0x8f2157
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: runtime/pprof.profileWriter(0x2c95700, 0xc004af5380)
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         /root/.gimme/versions/go1.15.8.linux.amd64/src/runtime/pprof/pprof.go:813 +0x105 fp=0xc075779fd0 sp=0xc075779f58 pc=0x8ef185
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: runtime.goexit()
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         /root/.gimme/versions/go1.15.8.linux.amd64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc075779fd8 sp=0xc075779fd0 pc=0x5f9761
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: created by runtime/pprof.StartCPUProfile
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]:         /root/.gimme/versions/go1.15.8.linux.amd64/src/runtime/pprof/pprof.go:784 +0x11f
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: goroutine 1 [chan receive, 20 minutes]:
Mar 18 15:02:57 i-0ddbd7bb67c8f786c mindy[79199]: main.main()
```

Linux version:
```
$ uname -a
Linux 4.4.0-1077-aws #87-Ubuntu SMP Wed Mar 6 00:03:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Is there anything I can do get more details on the crash?

**Comment by ianlancetaylor** [comment]
Thanks for reporting the problem.  This is golang/go#44971 and I think it will be dealt with by a change to the Go runtime rather than a change to cgosymbolizer.

**Comment by akrylysov** [comment]
@ianlancetaylor This still happens with latest Go https://github.com/golang/go/issues/44971#issuecomment-814989008
