### ISSUE TITLE
Basic usage failing to yield stack frames from C

### ISSUE THREAD

**Issue by scottopell** [ianlancetaylor/cgosymbolizer#18]
I have a small test app that I'm unable to get c stack frames from when utilizing this module.

I have a full repo with a dockerfile available [here](https://github.com/scottopell/cgosymbolizer-test-app).

Here's the short version, I have 2 source files, one in C and one in Go.

```c
#include <stdio.h>

typedef int (*myFuncDef)();

void __attribute__ ((noinline)) indirectionTwo() {
    myFuncDef funcPtr = NULL;
    fprintf(stderr, "Here: %d \n", funcPtr());
}


void __attribute__ ((noinline)) indirectionOne() {
    indirectionTwo();
}

void crash_now() {
    indirectionOne();
}
```

```go
package main

/*
void crash_now();
*/
import "C"

import (
	"fmt"

	_ "github.com/ianlancetaylor/cgosymbolizer"
)

func crash() {
	C.crash_now()
}

func main() {
	fmt.Println("Pre-crash")
	crash()
	fmt.Println("Post-crash")
}
```

And the resulting stack trace:
```
goroutine 1 [syscall]:
runtime.cgocall(0x481b10, 0x4000057ee8)
        /usr/lib/go-1.19/src/runtime/cgocall.go:158 +0x54 fp=0x4000057eb0 sp=0x4000057e70 pc=0x404c64
main._Cfunc_crash_now()
        _cgo_gotypes.go:41 +0x34 fp=0x4000057ee0 sp=0x4000057eb0 pc=0x4819c4
main.crash()
        /home/lima.linux/dev/cgosymbolizertest/crash.go:15 +0x1c fp=0x4000057ef0 sp=0x4000057ee0 pc=0x481a1c
main.main()
        /home/lima.linux/dev/cgosymbolizertest/crash.go:20 +0x64 fp=0x4000057f70 sp=0x4000057ef0 pc=0x481aa4
runtime.main()
        /usr/lib/go-1.19/src/runtime/proc.go:250 +0x254 fp=0x4000057fd0 sp=0x4000057f70 pc=0x4354f4
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000057fd0 sp=0x4000057fd0 pc=0x45e854
```

Is it correct to expect frames from a C source file in that stack trace?
Any advice on how I can debug this further?

**Comment by ianlancetaylor** [comment]
The unwinder will see a PC value of zero on the stack, and is unable to wind past that.  It has no information about a function at address 0, so the effect is that you don't see anything.

If you change your code to something like

```C
char *p;

void __attribute__ ((noinline)) indirectionTwo() {
    *p = '\0';
}
```

you should see at least some C stack frames on the stack.

**Comment by scottopell** [comment]
thanks! Can confirm that yields some C stack frames
```
goroutine 1 [syscall]:
crash_now
        /home/lima.linux/dev/cgosymbolizertest/crash.c:6 pc=0x481b88
runtime.cgocall(0x481b50, 0x4000057ee8)
        /usr/lib/go-1.19/src/runtime/cgocall.go:158 +0x54 fp=0x4000057eb0 sp=0x4000057e70 pc=0x404ca4
main._Cfunc_entryPoint()
        _cgo_gotypes.go:41 +0x34 fp=0x4000057ee0 sp=0x4000057eb0 pc=0x481a04
main.crash()
        /home/lima.linux/dev/cgosymbolizertest/crash.go:16 +0x1c fp=0x4000057ef0 sp=0x4000057ee0 pc=0x481a5c
main.main()
        /home/lima.linux/dev/cgosymbolizertest/crash.go:21 +0x64 fp=0x4000057f70 sp=0x4000057ef0 pc=0x481ae4
runtime.main()
        /usr/lib/go-1.19/src/runtime/proc.go:250 +0x254 fp=0x4000057fd0 sp=0x4000057f70 pc=0x435534
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000057fd0 sp=0x4000057fd0 pc=0x45e894
```

I do see _more_ C stack frames in GDB's backtrace (all 4 c functions vs just the crashing one), but that's probably a separate issue
